# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-27 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20191027_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
